### ISSUE TITLE
SameSite Cookie Flag Set-Cookie incorrectly

### ISSUE THREAD

**Issue by ottsgithub** [cloudkucooland/WASABI#5]
**Describe the bug**
https://qbin.phtiv.com:8000/privacy posted a cookie named WASABI that has the SameSite flag set wrong. 
**To Reproduce**
1. Go to '..'ttps://qbin.phtiv.com:8000/privacy 
2. open cookie
3. samesite

**Expected behavior**
A new http security feature preventing cross site request forgery. The value can be set to Strict or Lax.

Example with SameSite:
Set-Cookie: jsessionid=oIZEL75SLnw; HttpOnly; Secure; SameSite=Strict

Use this website as a good guide: https://medium.com/compass-security/samesite-cookie-attribute-33b3bfeaeb95

**Comment by cloudkucooland** [comment]
Need to test. probably can't be used due to IITC Cross-Site requirements.

**Comment by cloudkucooland** [comment]
https://github.com/gorilla/sessions

Cannot adjust this flag without a change being made in Gorilla Sessions. The cookie is encrypted, the nonce in the cookie is hashed. The worst that happens is someone sets a garbage cookie that gets deleted the first time it is passed to the server.

Non-issue.
