### ISSUE TITLE
X-Frame-Options missing

### ISSUE THREAD

**Issue by ottsgithub** [cloudkucooland/WASABI#6]
**Describe the bug**
From debug showing missing X-FRame-Options" header which indicates to the browser if it should be allowed to load your site inside of a frame of iFrame. Right now I could embed this site inside of another site without your permission. 

***Fix*** configure the web server to include the x-frame-header option so you don't get Clickjacked.

**Comment by cloudkucooland** [comment]
https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/X-Frame-Options

done
