### ISSUE TITLE
https://qbin.phtiv.com:8000/favicon.ico  

### ISSUE THREAD

**Issue by ottsgithub** [cloudkucooland/WASABI#7]
**Describe the bug**
https://qbin.phtiv.com:8000/favicon.ico   links to nowhere  404: No light here.

**To Reproduce**
debug site, find broken link: https://qbin.phtiv.com:8000/favicon.ico   / leads to 404: NO light here. 

**Expected behavior**
should link to *.ico files intended 

GET https://qbin.phtiv.com:8000/favicon.ico 404  returns nothing

**Comment by cloudkucooland** [comment]
not an issue. 404 is fine.

**Comment by ottsgithub** [comment]
Just a missing image.

All best,

Sean Gaines
sean.dgaines@gmail.com
