### ISSUE TITLE
Referrer Policy: no-referrer-when-downgrade

### ISSUE THREAD

**Issue by ottsgithub** [cloudkucooland/WASABI#8]
**Describe the bug**
Request URL: https://play.google.com/log?format=json&hasfast=true
Request Method: POST
Status Code: 401 
Remote Address: 172.217.2.238:443
Referrer Policy: no-referrer-when-downgrade

**To Reproduce**
https://play.google.com/log?format=json&hasfast=true

Provisional headers are shown
Authorization: SAPISIDHASH 02a019c16b417439c974cf30e22759ab89b21640
Content-Type: application/x-www-form-urlencoded;charset=UTF-8
DNT: 1
Origin: https://accounts.google.com
Referer: https://accounts.google.com/signin/oauth/identifier?client_id=269534461245-jbnes60ebd7u0b8naba19h4vqm7ji219.apps.googleusercontent.com&as=Y_8MOgXrW1CUofZ-xkxRWA&destination=https%3A%2F%2Fqbin.phtiv.com%3A8443&approval_state=!ChR1bjNibUVRbUtfdXdtTk9ad0lLZhIfbzRtUWlFSU1PcjhjVUEyYUd3VDlRSnpnNWxQTHBCWQ%E2%88%99AJDr988AAAAAXMD80zzJ8MrrugrkPL6luj7nXusWk-9e&oauthgdpr=1&xsrfsig=ChkAeAh8Ty5_r0UoxJcnMSpOkKfYB2pS44RaEg5hcHByb3ZhbF9zdGF0ZRILZGVzdGluYXRpb24SBXNvYWN1Eg9vYXV0aHJpc2t5c2NvcGU&flowName=GeneralOAuthFlow
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/73.0.3683.103 Safari/537.36

**Comment by cloudkucooland** [comment]
Google URL, not me

**Comment by ottsgithub** [comment]
this will help you with it: https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Referrer-Policy

https://www.w3.org/TR/referrer-policy/
