### ISSUE TITLE
o-auth issue - Google Login Integration 

### ISSUE THREAD

**Issue by ottsgithub** [cloudkucooland/WASABI#9]
on debug I get this big login error 

/accounts/static/_/js/k=gaia.gaiafe_glif.en.w6Igbvs7PAM.O/am=AASAAAAAAJQ3AACACEAA6RNDL-83EAAAAMFQdl80BKE/rt=j/d=1/rs=ABkqax1ulrV9tFdz9Ff5JMy6YIwL1me0Ew/m=glifb,identifier,unknownerror:363 POST https://play.google.com/log?format=json&hasfast=true 401

_.Mq.send | @ | /accounts/static/_/j…er,unknownerror:363
-- | -- | --
  | _.Vq | @ | /accounts/static/_/j…er,unknownerror:360
  | QAa | @ | /accounts/static/_/j…r,unknownerror:1547
  | OK.flush | @ | /accounts/static/_/j…r,unknownerror:1553
  | (anonymous) | @ | /accounts/static/_/j…er,unknownerror:245
  | wo | @ | /accounts/static/_/j…er,unknownerror:283
  | _.h.dispatchEvent | @ | /accounts/static/_/j…er,unknownerror:282
  | _.h.W5 | @ | /accounts/static/_/j…er,unknownerror:285
  | c | @ | /accounts/static/_/j…er,unknownerror:508
  | setTimeout (async) |   |  
  | c.(anonymous function) | @ | /accounts/static/_/j…er,unknownerror:509
  | _.h.start | @ | /accounts/static/_/j…er,unknownerror:285
  | OK.log | @ | /accounts/static/_/j…r,unknownerror:1550
  | _.iBa | @ | /accounts/static/_/j…r,unknownerror:1559
  | _.h.Ly | @ | /accounts/static/_/j…r,unknownerror:1559
  | (anonymous) | @ | /accounts/static/_/j…r,unknownerror:1557
  | e.aa | @ | /accounts/static/_/j…er,unknownerror:255
  | Iea | @ | /accounts/static/_/j…er,unknownerror:259
  | Eea | @ | /accounts/static/_/j…er,unknownerror:258
  | _.ma.ta | @ | /accounts/static/_/j…er,unknownerror:258
  | vea | @ | /accounts/static/_/j…er,unknownerror:250
  | Promise.then (async) |   |  
  | Jn | @ | /accounts/static/_/j…er,unknownerror:250
  | Ln | @ | /accounts/static/_/j…er,unknownerror:250
  | Fea | @ | /accounts/static/_/j…er,unknownerror:258
  | Mn | @ | /accounts/static/_/j…er,unknownerror:257
  | (anonymous) | @ | /accounts/static/_/j…er,unknownerror:251
  | Efa | @ | /accounts/static/_/j…er,unknownerror:309
  | tp | @ | /accounts/static/_/j…er,unknownerror:307
  | _.rp.callback | @ | /accounts/static/_/j…er,unknownerror:307
  | Pt.execute | @ | /accounts/static/_/j…er,unknownerror:477
  | c | @ | /accounts/static/_/j…er,unknownerror:508
  | Rt | @ | /accounts/static/_/j…er,unknownerror:478
  | Tia | @ | /accounts/static/_/j…er,unknownerror:477
  | Tt.$ | @ | /accounts/static/_/j…er,unknownerror:486
  | (anonymous) | @ | m=sygp,otPmVb,rlNAl:8
  | (anonymous) | @ | m=sygp,otPmVb,rlNAl:17

https://developers.google.com/web/tools/chrome-devtools/network/reference#timing-explanation

/accounts/static/_/js/k=gaia.gaiafe_glif.en.w6Igbvs7PAM.O/am=AASAAAAAAJQ3AACACEAA6RNDL-83EAAAAMFQdl80BKE/rt=j/d=1/rs=ABkqax1ulrV9tFdz9Ff5JMy6YIwL1me0Ew/m=glifb,identifier,unknownerror:363 POST https://play.google.com/log?format=json&hasfast=true 401
_.Mq.send @ /accounts/static/_/js/k=gaia.gaiafe_glif.en.w6Igbvs7PAM.O/am=AASAAAAAAJQ3AACACEAA6RNDL-83EAAAAMFQdl80BKE/rt=j/d=1/rs=ABkqax1ulrV9tFdz9Ff5JMy6YIwL1me0Ew/m=glifb,identifier,unknownerror:363
_.Vq @ /accounts/static/_/js/k=gaia.gaiafe_glif.en.w6Igbvs7PAM.O/am=AASAAAAAAJQ3AACACEAA6RNDL-83EAAAAMFQdl80BKE/rt=j/d=1/rs=ABkqax1ulrV9tFdz9Ff5JMy6YIwL1me0Ew/m=glifb,identifier,unknownerror:360
QAa @ /accounts/static/_/js/k=gaia.gaiafe_glif.en.w6Igbvs7PAM.O/am=AASAAAAAAJQ3AACACEAA6RNDL-83EAAAAMFQdl80BKE/rt=j/d=1/rs=ABkqax1ulrV9tFdz9Ff5JMy6YIwL1me0Ew/m=glifb,identifier,unknownerror:1547
OK.flush @ /accounts/static/_/js/k=gaia.gaiafe_glif.en.w6Igbvs7PAM.O/am=AASAAAAAAJQ3AACACEAA6RNDL-83EAAAAMFQdl80BKE/rt=j/d=1/rs=ABkqax1ulrV9tFdz9Ff5JMy6YIwL1me0Ew/m=glifb,identifier,unknownerror:1553
(anonymous) @ /accounts/static/_/js/k=gaia.gaiafe_glif.en.w6Igbvs7PAM.O/am=AASAAAAAAJQ3AACACEAA6RNDL-83EAAAAMFQdl80BKE/rt=j/d=1/rs=ABkqax1ulrV9tFdz9Ff5JMy6YIwL1me0Ew/m=glifb,identifier,unknownerror:245
wo @ /accounts/static/_/js/k=gaia.gaiafe_glif.en.w6Igbvs7PAM.O/am=AASAAAAAAJQ3AACACEAA6RNDL-83EAAAAMFQdl80BKE/rt=j/d=1/rs=ABkqax1ulrV9tFdz9Ff5JMy6YIwL1me0Ew/m=glifb,identifier,unknownerror:283
_.h.dispatchEvent @ /accounts/static/_/js/k=gaia.gaiafe_glif.en.w6Igbvs7PAM.O/am=AASAAAAAAJQ3AACACEAA6RNDL-83EAAAAMFQdl80BKE/rt=j/d=1/rs=ABkqax1ulrV9tFdz9Ff5JMy6YIwL1me0Ew/m=glifb,identifier,unknownerror:282
_.h.W5 @ /accounts/static/_/js/k=gaia.gaiafe_glif.en.w6Igbvs7PAM.O/am=AASAAAAAAJQ3AACACEAA6RNDL-83EAAAAMFQdl80BKE/rt=j/d=1/rs=ABkqax1ulrV9tFdz9Ff5JMy6YIwL1me0Ew/m=glifb,identifier,unknownerror:285
c @ /accounts/static/_/js/k=gaia.gaiafe_glif.en.w6Igbvs7PAM.O/am=AASAAAAAAJQ3AACACEAA6RNDL-83EAAAAMFQdl80BKE/rt=j/d=1/rs=ABkqax1ulrV9tFdz9Ff5JMy6YIwL1me0Ew/m=glifb,identifier,unknownerror:508
setTimeout (async)
c.(anonymous function) @ /accounts/static/_/js/k=gaia.gaiafe_glif.en.w6Igbvs7PAM.O/am=AASAAAAAAJQ3AACACEAA6RNDL-83EAAAAMFQdl80BKE/rt=j/d=1/rs=ABkqax1ulrV9tFdz9Ff5JMy6YIwL1me0Ew/m=glifb,identifier,unknownerror:509
_.h.start @ /accounts/static/_/js/k=gaia.gaiafe_glif.en.w6Igbvs7PAM.O/am=AASAAAAAAJQ3AACACEAA6RNDL-83EAAAAMFQdl80BKE/rt=j/d=1/rs=ABkqax1ulrV9tFdz9Ff5JMy6YIwL1me0Ew/m=glifb,identifier,unknownerror:285
OK.log @ /accounts/static/_/js/k=gaia.gaiafe_glif.en.w6Igbvs7PAM.O/am=AASAAAAAAJQ3AACACEAA6RNDL-83EAAAAMFQdl80BKE/rt=j/d=1/rs=ABkqax1ulrV9tFdz9Ff5JMy6YIwL1me0Ew/m=glifb,identifier,unknownerror:1550
_.iBa @ /accounts/static/_/js/k=gaia.gaiafe_glif.en.w6Igbvs7PAM.O/am=AASAAAAAAJQ3AACACEAA6RNDL-83EAAAAMFQdl80BKE/rt=j/d=1/rs=ABkqax1ulrV9tFdz9Ff5JMy6YIwL1me0Ew/m=glifb,identifier,unknownerror:1559
_.h.Ly @ /accounts/static/_/js/k=gaia.gaiafe_glif.en.w6Igbvs7PAM.O/am=AASAAAAAAJQ3AACACEAA6RNDL-83EAAAAMFQdl80BKE/rt=j/d=1/rs=ABkqax1ulrV9tFdz9Ff5JMy6YIwL1me0Ew/m=glifb,identifier,unknownerror:1559
(anonymous) @ /accounts/static/_/js/k=gaia.gaiafe_glif.en.w6Igbvs7PAM.O/am=AASAAAAAAJQ3AACACEAA6RNDL-83EAAAAMFQdl80BKE/rt=j/d=1/rs=ABkqax1ulrV9tFdz9Ff5JMy6YIwL1me0Ew/m=glifb,identifier,unknownerror:1557
e.aa @ /accounts/static/_/js/k=gaia.gaiafe_glif.en.w6Igbvs7PAM.O/am=AASAAAAAAJQ3AACACEAA6RNDL-83EAAAAMFQdl80BKE/rt=j/d=1/rs=ABkqax1ulrV9tFdz9Ff5JMy6YIwL1me0Ew/m=glifb,identifier,unknownerror:255
Iea @ /accounts/static/_/js/k=gaia.gaiafe_glif.en.w6Igbvs7PAM.O/am=AASAAAAAAJQ3AACACEAA6RNDL-83EAAAAMFQdl80BKE/rt=j/d=1/rs=ABkqax1ulrV9tFdz9Ff5JMy6YIwL1me0Ew/m=glifb,identifier,unknownerror:259
Eea @ /accounts/static/_/js/k=gaia.gaiafe_glif.en.w6Igbvs7PAM.O/am=AASAAAAAAJQ3AACACEAA6RNDL-83EAAAAMFQdl80BKE/rt=j/d=1/rs=ABkqax1ulrV9tFdz9Ff5JMy6YIwL1me0Ew/m=glifb,identifier,unknownerror:258
_.ma.ta @ /accounts/static/_/js/k=gaia.gaiafe_glif.en.w6Igbvs7PAM.O/am=AASAAAAAAJQ3AACACEAA6RNDL-83EAAAAMFQdl80BKE/rt=j/d=1/rs=ABkqax1ulrV9tFdz9Ff5JMy6YIwL1me0Ew/m=glifb,identifier,unknownerror:258
vea @ /accounts/static/_/js/k=gaia.gaiafe_glif.en.w6Igbvs7PAM.O/am=AASAAAAAAJQ3AACACEAA6RNDL-83EAAAAMFQdl80BKE/rt=j/d=1/rs=ABkqax1ulrV9tFdz9Ff5JMy6YIwL1me0Ew/m=glifb,identifier,unknownerror:250
Promise.then (async)
Jn @ /accounts/static/_/js/k=gaia.gaiafe_glif.en.w6Igbvs7PAM.O/am=AASAAAAAAJQ3AACACEAA6RNDL-83EAAAAMFQdl80BKE/rt=j/d=1/rs=ABkqax1ulrV9tFdz9Ff5JMy6YIwL1me0Ew/m=glifb,identifier,unknownerror:250
Ln @ /accounts/static/_/js/k=gaia.gaiafe_glif.en.w6Igbvs7PAM.O/am=AASAAAAAAJQ3AACACEAA6RNDL-83EAAAAMFQdl80BKE/rt=j/d=1/rs=ABkqax1ulrV9tFdz9Ff5JMy6YIwL1me0Ew/m=glifb,identifier,unknownerror:250
Fea @ /accounts/static/_/js/k=gaia.gaiafe_glif.en.w6Igbvs7PAM.O/am=AASAAAAAAJQ3AACACEAA6RNDL-83EAAAAMFQdl80BKE/rt=j/d=1/rs=ABkqax1ulrV9tFdz9Ff5JMy6YIwL1me0Ew/m=glifb,identifier,unknownerror:258
Mn @ /accounts/static/_/js/k=gaia.gaiafe_glif.en.w6Igbvs7PAM.O/am=AASAAAAAAJQ3AACACEAA6RNDL-83EAAAAMFQdl80BKE/rt=j/d=1/rs=ABkqax1ulrV9tFdz9Ff5JMy6YIwL1me0Ew/m=glifb,identifier,unknownerror:257
(anonymous) @ /accounts/static/_/js/k=gaia.gaiafe_glif.en.w6Igbvs7PAM.O/am=AASAAAAAAJQ3AACACEAA6RNDL-83EAAAAMFQdl80BKE/rt=j/d=1/rs=ABkqax1ulrV9tFdz9Ff5JMy6YIwL1me0Ew/m=glifb,identifier,unknownerror:251
Efa @ /accounts/static/_/js/k=gaia.gaiafe_glif.en.w6Igbvs7PAM.O/am=AASAAAAAAJQ3AACACEAA6RNDL-83EAAAAMFQdl80BKE/rt=j/d=1/rs=ABkqax1ulrV9tFdz9Ff5JMy6YIwL1me0Ew/m=glifb,identifier,unknownerror:309
tp @ /accounts/static/_/js/k=gaia.gaiafe_glif.en.w6Igbvs7PAM.O/am=AASAAAAAAJQ3AACACEAA6RNDL-83EAAAAMFQdl80BKE/rt=j/d=1/rs=ABkqax1ulrV9tFdz9Ff5JMy6YIwL1me0Ew/m=glifb,identifier,unknownerror:307
_.rp.callback @ /accounts/static/_/js/k=gaia.gaiafe_glif.en.w6Igbvs7PAM.O/am=AASAAAAAAJQ3AACACEAA6RNDL-83EAAAAMFQdl80BKE/rt=j/d=1/rs=ABkqax1ulrV9tFdz9Ff5JMy6YIwL1me0Ew/m=glifb,identifier,unknownerror:307
Pt.execute @ /accounts/static/_/js/k=gaia.gaiafe_glif.en.w6Igbvs7PAM.O/am=AASAAAAAAJQ3AACACEAA6RNDL-83EAAAAMFQdl80BKE/rt=j/d=1/rs=ABkqax1ulrV9tFdz9Ff5JMy6YIwL1me0Ew/m=glifb,identifier,unknownerror:477
c @ /accounts/static/_/js/k=gaia.gaiafe_glif.en.w6Igbvs7PAM.O/am=AASAAAAAAJQ3AACACEAA6RNDL-83EAAAAMFQdl80BKE/rt=j/d=1/rs=ABkqax1ulrV9tFdz9Ff5JMy6YIwL1me0Ew/m=glifb,identifier,unknownerror:508
Rt @ /accounts/static/_/js/k=gaia.gaiafe_glif.en.w6Igbvs7PAM.O/am=AASAAAAAAJQ3AACACEAA6RNDL-83EAAAAMFQdl80BKE/rt=j/d=1/rs=ABkqax1ulrV9tFdz9Ff5JMy6YIwL1me0Ew/m=glifb,identifier,unknownerror:478
Tia @ /accounts/static/_/js/k=gaia.gaiafe_glif.en.w6Igbvs7PAM.O/am=AASAAAAAAJQ3AACACEAA6RNDL-83EAAAAMFQdl80BKE/rt=j/d=1/rs=ABkqax1ulrV9tFdz9Ff5JMy6YIwL1me0Ew/m=glifb,identifier,unknownerror:477
Tt.$ @ /accounts/static/_/js/k=gaia.gaiafe_glif.en.w6Igbvs7PAM.O/am=AASAAAAAAJQ3AACACEAA6RNDL-83EAAAAMFQdl80BKE/rt=j/d=1/rs=ABkqax1ulrV9tFdz9Ff5JMy6YIwL1me0Ew/m=glifb,identifier,unknownerror:486
(anonymous) @ m=sygp,otPmVb,rlNAl:8
(anonymous) @ m=sygp,otPmVb,rlNAl:17

**Comment by ottsgithub** [comment]
![image](https://user-images.githubusercontent.com/47713482/56624409-52fe3200-65fe-11e9-8f87-b0edad9036ae.png)

**Comment by ottsgithub** [comment]
[](url)
![Annotation 2019-04-23 193127](https://user-images.githubusercontent.com/47713482/56624478-a40e2600-65fe-11e9-865f-f0e66ec2bcdd.jpeg)

**Comment by cloudkucooland** [comment]
That is all on Google's side. File the bug with them.

**Comment by ottsgithub** [comment]
Sorry, your site ;-)

**Comment by ottsgithub** [comment]
Actually, its not a Google bug, its in the code on your site. 
When I redirect my logins to Google got sign in to their vanity URL using SSO/SAML integration I don't see it throw that error. 
When I do the same actions on this site you can actually see the pause .. before it auth. 

But really, its not a Google issue. Please use these https://developers.google.com/web/tools/chrome-devtools/security/ and I'm happy to get on a one on one with you tomorrow and show you how I have the login setup in our app/lweb ogin page. Happy to let you use lucidchart as well. 

That link covers done earlier topics too.

**Comment by TheSned** [comment]
Works on my machine.
![image](https://user-images.githubusercontent.com/312193/56663278-554aa580-666b-11e9-879e-8ea8d8121f0d.png)
